# Generated by Django 4.0.2 on 2022-04-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_ofered', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Accept'), (2, 'Decline'), (3, 'Pending')], default=0)),
                ('new_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
