# Generated by Django 4.0.2 on 2022-04-13 04:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('condition', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('fixed_price', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, default='', upload_to='')),
                ('start_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=225)),
                ('log', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to=products.models.upload_to, verbose_name='image')),
                ('is_ofered', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category')),
            ],
        ),
    ]
